Added `@return $this` in `Message::withXXX ` methods PHPDoc
slimphp/Slim-Psr7 pull request #167
Opened 2020-09-26 22:03 UTC by noahboegli

Added `@return $this` in `Message::withXXX ` methods PHPDoc to allow for correct return type inheritance (in terms of IDE lookup systems).

This is in accordance with the [phpDocumentor documentation on Inhertance](https://docs.phpdoc.org/latest/guides/inheritance.html).

It fixes #146 

I'm available if anything needs to be done to get this accepted. 

Cheers

2020-10-09 08:43 UTC, noahboegli commented
@l0gicgate Sorry for the ping. Could this be looked into for merging in the following days? Cheers.

2020-10-12 21:06 UTC, l0gicgate requested changes
Can we return `static` instead of `$this` please?

2020-10-13 06:35 UTC, noahboegli commented
Sure, here you go.

2020-10-13 19:05 UTC, l0gicgate approved these changes

2020-10-13 19:06 UTC, merged