Added support others scheme
slimphp/Slim-Psr7 pull request #190
Opened 2021-04-12 13:38 UTC by Stilch

For example
```php
class WsUri extends Uri
{
    protected const VALID_SCHEME = [
        'ws' => 80,
        'wss' => 443,
    ];
}
```

2021-04-27 15:41 UTC, l0gicgate requested changes

2021-04-27 15:41 UTC, l0gicgate commented on src/Uri.php
> +    protected const SUPPORTED_SCHEME = [
this should be plural, I would also suggest making this public so it can be accessed for testing purposes/userland.

`SUPPORTED_SCHEMES`

2021-04-29 22:21 UTC, l0gicgate approved these changes

2021-04-29 22:22 UTC, merged

2021-05-09 06:07 UTC, Stilch commented on src/Uri.php
> +        if (!key_exists($scheme, self::SUPPORTED_SCHEMES)) {
Yes, you're right. I fix it.