Fix phpunit static provider
slimphp/Slim-Psr7 pull request #311
Opened 2024-06-09 10:46 UTC by williamdes

They should be static since a long time, phpunit is now unhappy if not static

Question: should we bump phpunit and migrate to annotations ?

2024-06-09 11:15 UTC, williamdes commented
I pushed one last commit to address newer phpunit deprecations.

```
4 tests triggered 8 PHPUnit deprecations:

1) Slim\Tests\Psr7\ResponseTest::testWithStatusValidReasonPhraseObject
* MockBuilder::addMethods() is deprecated and will be removed in PHPUnit 12 without replacement.

* returnValue() is deprecated and will be removed in PHPUnit 12. Use $double->willReturn() instead of $double->will($this->returnValue())

/mnt/Dev/@debian/@wdes-packaging-team/php-slim-psr7/tests/ResponseTest.php:142

2) Slim\Tests\Psr7\UriTest::testWithHostValidObject
* MockBuilder::addMethods() is deprecated and will be removed in PHPUnit 12 without replacement.

* returnValue() is deprecated and will be removed in PHPUnit 12. Use $double->willReturn() instead of $double->will($this->returnValue())

/mnt/Dev/@debian/@wdes-packaging-team/php-slim-psr7/tests/UriTest.php:134

3) Slim\Tests\Psr7\UriTest::testWithQueryValidObject
* MockBuilder::addMethods() is deprecated and will be removed in PHPUnit 12 without replacement.

* returnValue() is deprecated and will be removed in PHPUnit 12. Use $double->willReturn() instead of $double->will($this->returnValue())

/mnt/Dev/@debian/@wdes-packaging-team/php-slim-psr7/tests/UriTest.php:299

4) Slim\Tests\Psr7\UriTest::testWithFragmentValidObject
* MockBuilder::addMethods() is deprecated and will be removed in PHPUnit 12 without replacement.

* returnValue() is deprecated and will be removed in PHPUnit 12. Use $double->willReturn() instead of $double->will($this->returnValue())

/mnt/Dev/@debian/@wdes-packaging-team/php-slim-psr7/tests/UriTest.php:351

```

2024-07-10 08:58 UTC, williamdes commented
hello @akrabat 
what do you think about this PR and #310 ?

2024-07-11 07:31 UTC, akrabat requested changes

2024-07-11 07:31 UTC, akrabat commented on tests/TestObject.php
> +final class TestObject implements \Stringable
Can we rename to `StringableTestObject` or something along those lines? I'm not precious on the name, but something a little less generic would be helpful.

2024-07-11 09:45 UTC, williamdes commented on tests/TestObject.php
> +final class TestObject implements \Stringable
Good idea, I pushed a fix

2024-07-11 09:46 UTC, williamdes commented
I also did a bump for the workflows and removed the need to require a library to upload coverage, this will help when the code will get incompatible with the uploader module. Now you are sure to always be able to upload coverage.
See: https://github.com/coverallsapp/github-action

2024-07-11 09:55 UTC, akrabat approved these changes

2024-07-11 10:09 UTC, merged

2024-07-11 10:09 UTC, akrabat commented
Thanks.